
volumes:
  datafiles:

services:
 
  database:
   
    image: mysql:8.4.2
    
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/var/lib/mysql
      - ./sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: userroot
      MYSQL_PASSWORD: pass@word1234
      MYSQL_DATABASE: Usersdb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      DBHOST: database
      ASPNETCORE_ENVIRONMENT: Development
