volumes:
  datafiles:

services:
  database:
    image: mysql:8.4.2
    ports:
      - "3307:3306"
    volumes:
      - datafiles:/var/lib/mysql
      - ./sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: userroot
      MYSQL_PASSWORD: pass@word1234
      MYSQL_DATABASE: Usersdb

  migrations:
    container_name: service-migrations
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on:
      - database
    restart: "no"
    entrypoint:
      [
        "dotnet-ef",
        "database",
        "update",
        "--project",
        "FilmesApi.csproj",
        "--startup-project",
        "FilmesApi.csproj",
      ]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
    environment:
      DBHOST: database
      ASPNETCORE_ENVIRONMENT: Development
